# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/batuh/qt_designer/İnsta_bot/insta_bot.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 615)
        MainWindow.setStyleSheet("#centralwidget{\n"
"border-image: url(:/newPrefix/ıcon/bott_arkaplan.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_kullaniciAD = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kullaniciAD.setGeometry(QtCore.QRect(260, 100, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_kullaniciAD.setFont(font)
        self.lineEdit_kullaniciAD.setObjectName("lineEdit_kullaniciAD")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(255, 170, 0);")
        self.label.setObjectName("label")
        self.lineEdit_sifre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sifre.setGeometry(QtCore.QRect(260, 180, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sifre.setFont(font)
        self.lineEdit_sifre.setObjectName("lineEdit_sifre")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 180, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_2.setObjectName("label_2")
        self.lineEdit_hastag = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_hastag.setGeometry(QtCore.QRect(260, 290, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_hastag.setFont(font)
        self.lineEdit_hastag.setObjectName("lineEdit_hastag")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 240, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(255, 85, 255);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 550, 801, 31))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(550, 400, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_start.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"background-color: rgb(85, 170, 255);\n"
"background-color: rgb(85, 85, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ıcon/starticon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_start.setIcon(icon)
        self.pushButton_start.setObjectName("pushButton_start")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(260, 500, 281, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(300, 20, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(255, 85, 255);")
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 560, 141, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 340, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_7.setObjectName("label_7")
        self.lineEdit_yorum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_yorum.setGeometry(QtCore.QRect(260, 350, 271, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_yorum.setFont(font)
        self.lineEdit_yorum.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_yorum.setObjectName("lineEdit_yorum")
        self.checkBox_begen = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_begen.setGeometry(QtCore.QRect(200, 390, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_begen.setFont(font)
        self.checkBox_begen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_begen.setStyleSheet("color: rgb(255, 170, 0);")
        self.checkBox_begen.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../ıcon/like-dislike-icon-thumbs-down-600w-588372578.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_begen.setIcon(icon1)
        self.checkBox_begen.setIconSize(QtCore.QSize(40, 40))
        self.checkBox_begen.setTristate(False)
        self.checkBox_begen.setObjectName("checkBox_begen")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 400, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 26))
        self.menubar.setObjectName("menubar")
        self.menuYard_m = QtWidgets.QMenu(self.menubar)
        self.menuYard_m.setObjectName("menuYard_m")
        MainWindow.setMenuBar(self.menubar)
        self.actionNas_l_al_r = QtWidgets.QAction(MainWindow)
        self.actionNas_l_al_r.setObjectName("actionNas_l_al_r")
        self.action_leti_im = QtWidgets.QAction(MainWindow)
        self.action_leti_im.setObjectName("action_leti_im")
        self.menuYard_m.addAction(self.actionNas_l_al_r)
        self.menuYard_m.addAction(self.action_leti_im)
        self.menubar.addAction(self.menuYard_m.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_kullaniciAD.setPlaceholderText(_translate("MainWindow", "İnstagram Kullanıcı Adınız"))
        self.label.setText(_translate("MainWindow", "KULLANICI ADI :"))
        self.lineEdit_sifre.setPlaceholderText(_translate("MainWindow", "İnstagram Şifreniz"))
        self.label_2.setText(_translate("MainWindow", "ŞİFRE:"))
        self.lineEdit_hastag.setPlaceholderText(_translate("MainWindow", "#Yazılım"))
        self.label_3.setText(_translate("MainWindow", "Hedef Hesap Veya Hastag"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_start.setText(_translate("MainWindow", "BOTU BAŞLAT"))
        self.label_6.setText(_translate("MainWindow", "Giriş Bilgilerinizi Giriniz"))
        self.label_4.setText(_translate("MainWindow", "<u>2020 -- Batuhan Bağ  ©</u>"))
        self.label_7.setText(_translate("MainWindow", "YAZILACAK YORUM:"))
        self.lineEdit_yorum.setPlaceholderText(_translate("MainWindow", "Lütfen Yorumunuzu Giriniz"))
        self.label_8.setText(_translate("MainWindow", "GÖNDERİ BEĞEN:"))
        self.menuYard_m.setTitle(_translate("MainWindow", "Yardım"))
        self.actionNas_l_al_r.setText(_translate("MainWindow", "Nasıl Çalışır"))
        self.action_leti_im.setText(_translate("MainWindow", "İletişim"))

import icons_rc
